[tools]
deno = "latest"
hk = "latest"

[tasks.build-css]
description = "Build CSS from styles directory. Optionally compress with `--minify`"
run = "deno run --allow-read --allow-write ./scripts/build-css.ts"
sources = ["styles/**/*.css"]
