name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.x

      - name: Install dependencies
        run: |
          deno install
          deno task build:shared

      - name: Run Tests
        run: deno task test

      - name: Type Check
        run: deno task check

      - name: Check Format
        run: deno fmt --check

      - name: Install Playwright browsers
        run: deno run --allow-all npm:playwright install
      - name: Run e2e Tests
        run: deno task test:e2e
