name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.x

      - name: Install dependencies and build assets
        run: |
          deno install
          ./scripts/download-assets.sh
          deno task build:shared

      - name: Run Tests
        run: deno task test

      - name: Type Check
        run: deno task check

      - name: Check Format
        run: deno task fmt --check

      - name: Check Biome
        run: deno task biome:check

      - name: Install Playwright browser for headless Chrome (fastest install)
        run: deno run --allow-all npm:playwright install chromium --only-shell
      - name: Run e2e Tests
        run: deno task test:e2e --project=chrome
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
            test-results/
          retention-days: 1
